### ISSUE TITLE
你好，Type数据集中提供了传输图，您在训练Ucolor时，使用的时GDCP生成的传输图还是直接用Type数据集中的传输图？

### ISSUE THREAD

**Issue by Spacei567** [Li-Chongyi/Ucolor#12]
作者您好，由于您发表的UWCNN论文里制作的Type数据集中存在Tansmission Map，您的Ucolor论文里提到要使用一部分Type数据集进行训练，请问您在训练Ucolor时使用的传输图来自GDCP生成还是直接用Type数据集中的传输图？毕竟GDCP生成的传输图和Type中给传输图的质量是不一样的，您当时是选的哪个？期待您的回复，因为这真的对我很重要。

**Comment by Li-Chongyi** [comment]
当时用的GDCP的图。

Spacei567 ***@***.***> 于2023年2月27日周一 11:21写道：

**Comment by Spacei567** [comment]
太感谢您的回复了！
