### ISSUE TITLE
请问有Pytorch版本的实现吗

### ISSUE THREAD

**Issue by Surrin1999** [Li-Chongyi/Ucolor#7]
如题，之前看您的Water-Net有Pytorch实现，请问Ucolor有没有呢？

**Comment by Li-Chongyi** [comment]
Ucolor 我们还没有pytorch的 目前有 TensorFlow 还有 华为的Mindspore 版本的。Mindspore 刚刚更新。

Surrin1999 ***@***.***> 于2021年10月25日周一 下午8:49写道：
